---
ansible_host: 192.168.200.11
ansible_user: root
ansible_ssh_pass: opnsense

opn_general:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: firewall2
      - key: domain
        value: naturalis.nl
  - xpath: /opnsense/nat
    settings:
      - key: outbound/mode
        value: disabled

opn_vlan_parent_interface: vtnet2

opn_interfaces:
  - interface: wan
    settings:
      - key: if
        value: vtnet1
      - key: ipaddr
        value: 172.16.10.2
      - key: subnet
        value: 24
      - key: gateway
        value: wan_gateway
      - key: descr
        value: wan
  - interface: lan
    settings:
      - key: if
        value: vtnet2
      - key: ipaddr
        value: 192.168.1.2
      - key: subnet
        value: 24
      - key: descr
        value: lan
  - interface: sync
    settings:
      - key: if
        value: vtnet3
      - key: ipaddr
        value: 192.168.254.1
      - key: enable
        value: 1
      - key: subnet
        value: 30
      - key: descr
        value: sync

opn_filter:
  - descr: Allow sync
    settings:
      - key: interface
        value: sync
      - key: log
        value: 1
      - key: type
        value: pass
      - key: ipprotocol
        value: inet
      - key: statetype
        value: keep state
      - key: source/any
        value: 1
      - key: destination/any
        value: 1

opn_syslog:
  - xpath: /opnsense/syslog
    settings:
      - key: reverse
        value: 1
      - key: nentries
        value: 50
      - key: remoteserver
        value: 192.168.200.254
      - key: sourceip
        value: oob
      - key: ipproto
        value: ipv4
      - key: logall
        value: 1
      - key: enable
        value: 1
...
