---
ansible_host: 192.168.200.12
ansible_user: root
ansible_ssh_pass: opnsense

opn_general:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: firewall1
      - key: domain
        value: naturalis.nl

opn_vlan_parent_interface: vtnet2

opn_interfaces:
  - interface: lan
    settings:
      - key: if
        value: vtnet2
      - key: ipaddr
        value: 172.16.1.1
      - key: subnet
        value: 30
      - key: descr
        value: LAN
  - interface: pfsync
    settings:
      - key: if
        value: vtnet3
      - key: ipaddr
        value: 192.168.254.1
      - key: enable
        value: 1
      - key: subnet
        value: 30
      - key: descr
        value: SYNC

opn_syslog:
  - xpath: /opnsense/syslog
    settings:
      - key: reverse
        value: 1
      - key: nentries
        value: 50
      - key: remoteserver
        value: 192.168.200.254
      - key: sourceip
        value: OOB
      - key: ipproto
        value: ipv4
      - key: logall
        value: 1
      - key: enable
        value: 1
...
