---
lo: 127.0.0.1/8
rsyslog_interface: swp47
snmp_listen: 145.136.246.202
ospf:
  swp47:
    router-address: 172.16.20.11/24
    network: '172.16.20.0/24'
  vlan250:
    vlan: 250
    router-address: 172.16.250.1/24
    network: '172.16.250.0/24'
mlag:
  primary: true
  members:
  - swp49
  - swp50
  address: 169.254.1.1/30
  peer-ip: 169.254.1.2
  backup-ip: 192.168.200.3
  sysmac: 44:38:39:FF:FA:01
  priority: 4096
svi:
  10:
    ipv4-virtual: 172.16.10.11/24
    ipv4: 172.16.10.12/24
aggregation_ports:
  ser-a:
    mlag: true
    mlag-id: 2
    members:
    - swp1
    trunk: true
  swp45:
    trunk: false
    vlan: 10
  fw-inside:
    mlag: true
    mlag-id: 46
    members:
    - swp46
    trunk: true
...
