Vagrant.configure("2") do |config|
  config.vm.box = "rudibroekhuizen/opnsense"
  config.vm.box_version = "19.1"

  config.vm.define 'opnsense', autostart: false do |test|
    # setup network
    test.vm.provider 'virtualbox' do |vb|
      vb.customize ['modifyvm',:id, '--nic2', 'intnet', '--nicpromisc2', 'allow-all', '--intnet2', '1542360080_net3']
      # pfsync
      vb.customize ['modifyvm',:id, '--nic3', 'intnet', '--nicpromisc3', 'allow-all', '--intnet3', '1542360080_net73']
    end
  end  
end
