---
# This is used to manage Ansible role dependences
# http://docs.ansible.com/galaxy.html#installing-multiple-roles-from-a-file
# Install with: ansible-galaxy install -r requirements.yml --roles-path .

- name: ansible-cumulus
  src: https://github.com/naturalis/ansible-cumulus
  version: v1.1

- name: ansible-opnsense
  src: https://github.com/naturalis/ansible-opnsense
  version: v1.3
...
