Vagrant.configure("2") do |config|


  simid = 1552905337


  config.vm.box = "rudibroekhuizen/opnsense"
  config.vm.box_version = "1.0.opnsense.19.1"
  #config.vm.boot_timeout = 15
  
  # firewall1
  config.vm.define 'firewall1' do |config|
    config.vm.provider 'virtualbox' do |vb|
      vb.name = "#{simid}_firewall1"
      #nic1, vagrant, already configured in box
      #nic2, oob
      vb.customize ['modifyvm', :id, '--nic2', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet2', "#{simid}_net30"]
      #nic3, wan, nat, already configured in box
      #nic4, lan (inside)
      vb.customize ['modifyvm', :id, '--nic4', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet4', "#{simid}_net17"]
    end
  end

  # firewall2
  config.vm.define 'firewall2' do |config|
    config.vm.provider 'virtualbox' do |vb|
      vb.name = "#{simid}_firewall2"
      #nic1, vagrant, already configured in box
      #nic2, oob
      vb.customize ['modifyvm', :id, '--nic2', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet2', "#{simid}_net32"]
      #nic3, wan (outside)
      vb.customize ['modifyvm', :id, '--nic3', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet3', "#{simid}_net12"]
      #nic4, lan (inside)
      vb.customize ['modifyvm', :id, '--nic4', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet4', "#{simid}_net10"]
      #nic5, sync:
      vb.customize ["modifyvm", :id, "--nic5", "intnet"]
      vb.customize ["modifyvm", :id, "--intnet5", "sync"]
      vb.customize ["modifyvm", :id, "--nictype5", "virtio"]
      vb.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
    end
  end
  
  # firewall3
  config.vm.define 'firewall3' do |config|
    config.vm.provider 'virtualbox' do |vb|
      vb.name = "#{simid}_firewall3"
      #nic1, vagrant, already configured in box
      #nic2, oob
      vb.customize ['modifyvm', :id, '--nic2', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet2', "#{simid}_net31"]
      #nic3, wan (outside)
      vb.customize ['modifyvm', :id, '--nic3', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet3', "#{simid}_net7"]
      #nic4, lan (inside)
      vb.customize ['modifyvm', :id, '--nic4', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet4', "#{simid}_net14"]
      #nic5, sync:
      vb.customize ["modifyvm", :id, "--nic5", "intnet"]
      vb.customize ["modifyvm", :id, "--intnet5", "sync"]
      vb.customize ["modifyvm", :id, "--nictype5", "virtio"]
      vb.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]
    end
  end
end


#vb.customize ['modifyvm', :id, '--macaddress3', '443839000039']
