Vagrant.configure("2") do |config|

  simid = 1552905337

  config.vm.box = "rudibroekhuizen/opnsense"
  config.vm.box_version = "19.1"
  #config.vm.boot_timeout = 15
  
  # firewall1
  config.vm.define 'firewall1' do |config|
    config.vm.provider 'virtualbox' do |vb|
      vb.name = "#{simid}_firewall1"
      #nic1, oob
      vb.customize ['modifyvm', :id, '--nic1', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet1', "#{simid}_net30"]
      #nic2, wan, nat, already available in box
      #nic3, lan (inside)
      vb.customize ['modifyvm', :id, '--nic3', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet3', "#{simid}_net17"]
    end
  end

  # firewall2
  config.vm.define 'firewall2' do |config|
    config.vm.provider 'virtualbox' do |vb|
      vb.name = "#{simid}_firewall2"
      #nic1, oob
      vb.customize ['modifyvm', :id, '--nic1', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet1', "#{simid}_net32"]
      #nic2, wan (outside)
      vb.customize ['modifyvm', :id, '--nic2', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet2', "#{simid}_net12"]
      #nic3, lan (inside)
      vb.customize ['modifyvm', :id, '--nic3', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet3', "#{simid}_net10"]
    end
  end
  
  # firewall3
  config.vm.define 'firewall3' do |config|
    config.vm.provider 'virtualbox' do |vb|
      vb.name = "#{simid}_firewall3"
      #nic1, oob
      vb.customize ['modifyvm', :id, '--nic1', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet1', "#{simid}_net31"]
      #nic2, wan (outside)
      vb.customize ['modifyvm', :id, '--nic2', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet2', "#{simid}_net7"]
      #nic3, lan (inside)
      vb.customize ['modifyvm', :id, '--nic3', 'intnet']
      vb.customize ['modifyvm', :id, '--intnet3', "#{simid}_net14"]
    end
  end
end


#vb.customize ['modifyvm', :id, '--macaddress3', '443839000039']
