---
env: staging
mgmt_user: cumulus
admin_users:
- username: rudi.broekhuizen
  public_key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDeRrVuojExYBWgIV7UlLfYLvzGpW9hSzrjl9qJ7Kb3E/x+kq2ruma3LXlvMzFXoCKJMYvqvXUFj2Dzwh+iJ2bCyh5ilWgTMLvAwzRl1LdAV8IbDVYNZGCHCzXkyxLMAEdxXMHVYl6N/q+RBP+HQCySpwOjv86c5PgXoL4BOnxLy5TAoxSsfvxRcHT42ThYK1C/R5QC8UoBdpJ1RBhQRjBJPMWp9zRyOafNwE7Iti15gKHp04bn9UGqHRTA1ul+Q6YEFzjoqUxe4VCHObM6BS/DpD++TPMXjzU+aeJ8tkxhmYkGRKYJx/KK3uaKPv+/EkODePvwTVshiQ8v9qOXx0YJ
- username: foppe.pieters
  public_key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDSlxZ2l6LPr2200r+5DM0S3Emxl8fP4mH13BAHkC+UcxJ3BZiWXaveKa3LoN3Yh5PioNk8AXcHkQ9ijQduUbLNuTyrys2YfuFSdV/VKBBMjqk1GHPjeVLq1/k9RtcYDVXK7h3nmJBaqSbYUSLkYR9Ax/RN+hW+cxvVTmlsqOVRjLLjaopGZWUNyZRNXCOYfF+UD+L1WTbOiihwYtyeFOrzyerEwpWZGWoZs98sIWrfXVIAE4u7L6wz8y+KAITvjHRscEjza6ZU+MfFkhg2OehDjLni17Y1+c1QVpeLf1z2PgqJjzJhW0bhJvQJaE8+1w1vhKlCc8Y98Ny5mPupb4pB
vlans:
  10:
    name: vlan10
    subnet: 172.16.10.0/24
  51:
    name: vlan51
    subnet: 172.16.51.0/24
  52:
    name: vlan52
    subnet: 172.16.52.0/24
  53:
    name: vlan53
    subnet: 172.16.53.0/24
default_port_config: test
port_configs:
  test:
    untagged: 51
    tagged:
    - 52
    - 53
  vlan51:
    untagged: 51
  vlan52:
    untagged: 52
  vlan53:
    untagged: 53
