Vagrant.configure("2") do |config|
  
  
  simid = 1554727716
  
  
  config.vm.box = "peru/ubuntu-18.04-desktop-amd64"
  config.vm.define 'workstation1' do |config|
    config.vm.provider 'virtualbox' do |vb|
      vb.name = "#{simid}_workstation1"
      vb.customize ['modifyvm', :id, "--nic1", "intnet"]
      vb.customize ['modifyvm', :id, '--intnet1', "#{simid}_net8"]
    end
  end
  
  config.vm.define 'workstation3' do |config|
    config.vm.provider 'virtualbox' do |vb|
      vb.name = "#{simid}_workstation2"
      vb.customize ['modifyvm', :id, "--nic1", "intnet"]
      vb.customize ['modifyvm', :id, '--intnet1', "#{simid}_net18"]
    end
  end  
end
